### ISSUE TITLE
Question: How will this be used eventually?

### ISSUE THREAD

**Issue by pdgonzalez872** [cogini/nerves_init_ec2#1]
First off, this is awesome. The write up you did [here](https://www.cogini.com/blog/running-nerves-on-amazon-ec2/) is a great read.

With that out of the way, how do you see this integrated in the current nerves ecosystem? A lib we would pull in?

Thanks!

**Comment by reachfh** [comment]
This library makes it possible to run nerves apps in the cloud. It's equivalent to something like nerves_init_gadget, so it's easy to swap out. It may be useful for testing or development of Nerves applications.

My interest in this is as a way of creating minimal legacy-free systems. I think there is a lot to be learned from the embedded community and tools. They are naturally focused on supporting physical hardware devices, but cloud "hardware" is simpler. In the cloud, we don't need the same reliable firmware update process as for embedded systems. We can easily create new instances rather than upgrading existing ones. I am not sure if it's better to have Elixir handle the system initialization work or do it in systemd.

My plans are:
* Look at nerves_runtime and see what can be simplified, try to run as a non-root user
* Look at supporting CodeDeploy for blue/green deployment of code
* Integrate logging via CloudWatch Logs
* See if the Nerves build process can be leveraged to build non-embedded apps and deploy firmware as AMIs

**Comment by pdgonzalez872** [comment]
Fantastic! Thanks for the info!
